bitrock_folder: 'c:/sam/fix/installers/mtnsmartclient/mtnkyc/2.4/databases'
bitrock_project_file: 'C:\fix\Installers\mtnsmartclient\smartclient-checks-and-balance.xml'
bitrock_builder_path: 'C:\Program Files (x86)\BitRock InstallBuilder Enterprise 7.2.6\bin'
bitrock_output_folder: 'C:\Users\Administrator\Documents\InstallBuilder\output'
bitrock_output_file: 'smartclient-2.0-windows-installer'
bitrock_output_file_extension: 'exe'
final_destination: 'C:\Bitnami\wampstack-5.6.28-1\apache2\htdocs\downloads\installers'
final_destination_url: 'https://asset.seamfix.com/downloads/installers'