---
ansible_user: 'seamkit2@mtn.com.ng'
ansible_password: 'We1c0me123@MTN'
ansible_port: 5986
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore
ansible_winrm_transport: credssp

memcached_services:
- KycMemcache01
- KycMemcache02
- KycMemcache03
- KycMemcache04
- KycMemcache05
- KycMemcache06
- KycMemcache07
- KycMemcache08