---
ansible_user: 'seamkit2@mtn.com.ng'
ansible_password: '*W3lc0m3@5432#'
ansible_port: 5986
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore
ansible_winrm_transport: credssp

memcached_services:
- KycMemcache01
- KycMemcache02
- KycMemcache03