---
ansible_user: 'seamkit2@mtn.com.ng'
ansible_password: 'Welcome123@#'
ansible_port: 5986
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore
ansible_winrm_transport: credssp

memcached_services:
- KycMemcached00
- KycMemcached01
- KycMemcached02
- KycMemcached03
- KycMemcached04
- KycMemcached05

sftp_locations:
- 172.16.5.237
- 172.16.5.240
- 172.16.5.241
- 172.16.5.242
- 172.16.8.233
- 172.16.111.222
- 172.16.111.223
- 172.16.111.224
- 172.16.111.225
- 172.16.8.232
- 172.16.8.233