---
ansible_user: 'seamkit2@mtn.com.ng'
ansible_password: 'We1c0me123@MTN'
ansible_port: 5986
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore
ansible_winrm_transport: credssp

memcached_services:
- MemCacheD_1
- MemCacheD_2