# These tasks are meant to restart memcache
# on any target server.

---
- hosts: '{{ target_host }}'
  serial: 10

  tasks:
  - name: Restart memcache service
    win_shell: Restart-Service '{{ item }}'
    with_items: '{{ memcached_services }}'
  ignore_errors: true
